#pragma once

#include "GPIO_Sysfs.h"

enum gpio_zynqberry_pxfmini {
    ZYNQBERRY_PXFMINI_GPIO_MPU_9250_DRDY,
    ZYNQBERRY_PXFMINI_GPIO_LED_AMBER,
    ZYNQBERRY_PXFMINI_GPIO_LED_BLUE,
    ZYNQBERRY_PXFMINI_GPIO_LED_YELLOW,
    ZYNQBERRY_PXFMINI_GPIO_PWM_EN,
    _ZYNQBERRY_PXFMINI_GPIO_MAX,
};

